version: '3.8'

services:
  db:
    container_name: jwt-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mathis
      MYSQL_DATABASE: userservice
    ports:
      - "3306:3306"

  app:
    container_name: jwt-spring-app
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.dev
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userservice
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
