version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mathis
      MYSQL_DATABASE: userservice
    volumes:
      - ./mysql/data:/var/lib/postgresql/data
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8088:8080"